#!/usr/bin/env bash

SOURCE=/autograder/source
SUBMISSION=/autograder/submission
RESULTS=/autograder/results

set -e

# Copy default results.json with error message in case anything fails before generating one
cp "$SOURCE/results.json" "$RESULTS/results.json"

source "$HOME/.cargo/env"

# Set submission as working directory
cd "$SUBMISSION" || exit

# Copy our tests
rm -rf tests
cp -r "$SOURCE/tests" tests

# Get a clean build in case they uploaded target/
cargo clean
if [ -f build.rs ]; then
    rm build.rs
fi
cargo build

# Run tests
cp "$SOURCE/run_tests.py" run_tests.py
python3 run_tests.py "$RESULTS/results.json"
